env:
  browser: true
  es2020: true
  node: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - standard
  - 'plugin:react-hooks/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      path:
        - src
  react:
    version: detect
rules:
  space-before-function-paren: off
  comma-dangle: off
  react/self-closing-comp:
    - error
    - component: true
      html: true
  react/no-unknown-property: error
  react/prop-types: off
  import/un-resolved: off
  import/order:
    - error
    - groups:
        - - builtin
          - external
          - internal
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  indent: off
  no-console: warn
