env:
  browser: true
  es2020: true
  node: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - standard
  - 'plugin:react-hooks/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      path:
        - src
  react:
    version: detect
rules:
  space-before-function-paren: 0
  comma-dangle: 0
  react/self-closing-comp:
    - error
    - component: true
      html: true
  react/no-unknown-property: error
  react/prop-types: 0
  import/un-resolved: 0
  import/order:
    - error
    - groups:
        - - builtin
          - external
          - internal
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars': error
  indent: 0
  no-console: warn
  no-useless-constructor: 0
