version: '3.8'
services:
  server:
    stdin_open: true
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - './server:/srv/server'
    environment:
      PORT: 3001
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './client:/srv/client'
    environment:
      REACT_APP_API_BASE_URL: http://localhost:3001
    depends_on:
      - server
